services:
  postgres:
    image: postgres:17
    container_name: postgres-financeiro
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_financeiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_local_123
    ports:
      - "5432:5432"
    volumes:
      - financeiro_postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: financeiro-pessoal-premium
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres_local_123@postgres:5432/app_financeiro?schema=public
      APP_EMAIL: admin@financeiro.local
      APP_PASSWORD: admin123456
      JWT_SECRET: local_secret_change_me_123456789_abcdef
      APP_NAME: Meu Financeiro
      PORT: 3000
      NODE_ENV: production
      COOKIE_SECURE: "false"
volumes:
  financeiro_postgres:
